[package]
name = "organ-packager"
version = "0.3.0"
edition = "2021"
authors = ["hrkcz001"]
license = "Apache-2.0"
description = "Universal package and organ manager for Presence (Scoop, SFSU, and Nix)"

[dependencies]
presence-organ-sdk = { path = "../../presence-organ-sdk", version = "0.3.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"